version: '3.9'
services:
  client:
    build: front-end
    ports:
      - "3000:3000"
  Comments:
    build: Comments
    ports:
      - "4001:4001"
    depends_on:
      - "eventbus"
  eventbus:
    build: event-bus
  CommentVoting:
    build: CommentVoting
    ports:
      - "4002:4002"
    depends_on:
      - "eventbus"
  Messages:
    build: Messages
    ports:
      - "4003:4003"
    depends_on:
      - "eventbus"
  MockElection:
    build: mock-election-jl
    ports:
      - "4004:4004"
    depends_on:
      - "eventbus"
  Moderation:
    build: Moderation
    ports:
      - "4005:4005"
    depends_on:
      - "eventbus"
  Threads:
    build: Threads
    ports:
      - "4006:4006"
    depends_on:
    - "eventbus"        
  trustDistinction:
      build: trust-distinction-jl
      ports:
        - "4007:4007"
      depends_on:
        - "eventbus"
  Users:
      build: Users
      ports:
        - "4008:4008"
      depends_on:
        - "eventbus"
  voteBreakdown:
      build: vote-breakdown-jl
      ports:
        - "4009:4009"
      depends_on:
        - "eventbus"
    
        
    