version: '3.9'
services:
  client:
    build: front-end
    ports:
      - "3000:3000"
  comments:
    build: services/comments
    ports:
      - "4001:4001"
    depends_on:
      - "eventbus"
  eventbus:
    build: services/event-bus
  commentvoting:
    build: services/commentVoting
    ports:
      - "4002:4002"
    depends_on:
      - "eventbus"
  messages:
    build: services/messages
    ports:
      - "4003:4003"
    depends_on:
      - "eventbus"
  mockelection:
    build: services/mockElection
    ports:
      - "4004:4004"
    depends_on:
      - "eventbus"
  moderation:
    build: services/moderation
    ports:
      - "4005:4005"
    depends_on:
      - "eventbus"
  threads:
    build: services/threads
    ports:
      - "4006:4006"
    depends_on:
    - "eventbus"        
  trustdistinction:
      build: services/trustDistinction
      ports:
        - "4007:4007"
      depends_on:
        - "eventbus"
  users:
      build: services/users
      ports:
        - "4008:4008"
      depends_on:
        - "eventbus"
  votebreakdown:
      build: services/voteBreakdown
      ports:
        - "4009:4009"
      depends_on:
        - "eventbus"
    
        
    